use base64::{engine::general_purpose::STANDARD as B64, Engine};
use futures_util::{Sink, SinkExt, StreamExt};
use reqwest::Client;
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use std::{fs, io::{Cursor, Read}, path::{Path, PathBuf}, sync::Arc, time::{Duration, SystemTime, UNIX_EPOCH}};
use tauri::{AppHandle, Emitter, Manager, State};
use thiserror::Error;
use tokio::{sync::{mpsc, Mutex, RwLock}, time::{sleep, timeout}};
use tokio_tungstenite::{connect_async, tungstenite::Message};
use uuid::Uuid;

#[derive(Debug, Error)]
enum AgentError { #[error("{0}")] Message(String), #[error(transparent)] Io(#[from] std::io::Error), #[error(transparent)] Json(#[from] serde_json::Error), #[error(transparent)] Http(#[from] reqwest::Error) }
type AgentResult<T> = std::result::Result<T, AgentError>;

#[derive(Clone, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Config { pub relay_public_base_url: String, pub auth_poll_interval_ms: u64, pub lockfile_path: Option<String>, pub prevent_queue_after_dodge: bool, pub apply_default_status_on_connect: bool, pub auto_accept_match: bool, pub follow_league_client: bool, pub update_manifest_url: Option<String>, pub check_updates_on_startup: bool, pub auto_update_enabled: bool, pub saved_session_max_age_days: u64, pub run_at_windows_startup: bool, pub ui_test_mode: bool }
impl Default for Config { fn default() -> Self { Self { relay_public_base_url:"https://yummi.duckdns.org".into(), auth_poll_interval_ms:1500, lockfile_path:None, prevent_queue_after_dodge:true, apply_default_status_on_connect:true, auto_accept_match:false, follow_league_client:true, update_manifest_url:Some("https://yummi.duckdns.org/agent/version.json".into()), check_updates_on_startup:true, auto_update_enabled:true, saved_session_max_age_days:14, run_at_windows_startup:true, ui_test_mode:false } } }
impl Config { fn path() -> PathBuf { std::env::current_exe().ok().and_then(|p|p.parent().map(Path::to_path_buf)).unwrap_or_default().join("agent.json") } fn secure_url(raw:&str)->String { let s=raw.trim().trim_end_matches('/'); if s.starts_with("http://localhost")||s.starts_with("http://127.0.0.1") { return s.into(); } s.replacen("http://", "https://", 1) } fn normalize(&mut self) { self.relay_public_base_url=Self::secure_url(&self.relay_public_base_url); self.update_manifest_url=self.update_manifest_url.as_ref().map(|s|Self::secure_url(s)); self.auto_update_enabled=true; } fn load()->Self { let mut c=fs::read_to_string(Self::path()).ok().and_then(|s|serde_json::from_str::<Config>(&s).ok()).unwrap_or_default(); c.normalize(); c } fn save(&self)->AgentResult<()> { fs::write(Self::path(), serde_json::to_string_pretty(self)?)?; Ok(()) } fn ws_url(&self,id:&str)->AgentResult<String>{ let u=url::Url::parse(&self.relay_public_base_url).map_err(|e|AgentError::Message(e.to_string()))?; let scheme=if u.scheme()=="https"{"wss"}else{"ws"}; Ok(format!("{}://{}/ws/agent?session_id={}",scheme,u.host_str().unwrap_or_default(),urlencoding(id))) } fn login_url(&self,id:&str)->String{format!("{}/login?session_id={}",self.relay_public_base_url,urlencoding(id))} fn auth_url(&self,id:&str)->String{format!("{}/auth/status?session_id={}",self.relay_public_base_url,urlencoding(id))} }
fn urlencoding(s:&str)->String { s.replace('%',"%25").replace(' ',"%20").replace('?',"%3F").replace('&',"%26").replace('=',"%3D") }
#[cfg(windows)] fn sync_windows_startup(enabled:bool)->AgentResult<()> { use std::os::windows::process::CommandExt; let exe=std::env::current_exe()?.to_string_lossy().to_string(); let mut c=std::process::Command::new("reg.exe"); c.creation_flags(0x08000000); if enabled { c.args(["add",r"HKCU\Software\Microsoft\Windows\CurrentVersion\Run","/v","YummiLcuAgent","/t","REG_SZ","/d",&exe,"/f"]); } else { c.args(["delete",r"HKCU\Software\Microsoft\Windows\CurrentVersion\Run","/v","YummiLcuAgent","/f"]); } if !c.status()?.success() && enabled { return Err(AgentError::Message("Windows 시작 프로그램 등록 실패".into())) } Ok(()) }
#[cfg(not(windows))] fn sync_windows_startup(_:bool)->AgentResult<()> { Ok(()) }

#[derive(Clone, Serialize)]
struct UiState { status:String, relay:bool, lcu:bool, discord_id:Option<u64>, discord_name:Option<String>, discord_avatar:Option<String>, logs:Vec<String>, oauth_pending:bool, app_version:String, downloaded_at:Option<u64>, config:Config }
fn installed_at()->Option<u64>{let exe=std::env::current_exe().ok()?;let meta=fs::metadata(exe).ok()?;let time=meta.created().or_else(|_|meta.modified()).ok()?;time.duration_since(UNIX_EPOCH).ok().map(|d|d.as_secs())}
impl UiState { fn new(c:Config)->Self{Self{status:"연결 시작 → Discord 로그인".into(),relay:false,lcu:false,discord_id:None,discord_name:None,discord_avatar:None,logs:vec![],oauth_pending:false,app_version:env!("CARGO_PKG_VERSION").into(),downloaded_at:installed_at(),config:c}} }
pub struct AgentState { config: RwLock<Config>, ui: Mutex<UiState>, cancel: Mutex<Option<tokio::sync::watch::Sender<bool>>>, oauth_tx: Mutex<Option<mpsc::Sender<String>>>, command_lock: Mutex<()> }
impl AgentState { async fn log(&self,app:&AppHandle,msg:impl Into<String>){let mut u=self.ui.lock().await;u.logs.push(msg.into());if u.logs.len()>300{u.logs.remove(0);}let _=app.emit("agent-state",u.clone());} async fn emit(&self,app:&AppHandle){let u=self.ui.lock().await;let _=app.emit("agent-state",u.clone());} }

fn allowed(action:&str)->bool { const A:&[&str]=&["ping","accept_match","decline_match","reconnect","dodge","queue_start","queue_cancel","leave_lobby","party_ready","champ_reroll","champ_select_action","set_summoner_spells","list_rune_pages","set_rune_page","get_current_rune_page","update_rune_page","quit_client","set_status","reset_status","claim_all_rewards","launch_client","create_ranked_lobby","create_normal_lobby","play_ranked_solo","play_normal_draft","invite_party_members","check_party_members"]; A.contains(&action) }

#[derive(Clone)] struct Lcu { port:u16, password:String, http:Client }
impl Lcu { fn from_lockfile(path:&Path)->AgentResult<Self>{let raw=fs::read_to_string(path).map_err(|_|AgentError::Message("lockfile 읽기 실패".into()))?;let p:Vec<_>=raw.trim().split(':').collect();if p.len()<4{return Err(AgentError::Message("lockfile 형식 오류".into()))}let port=p[2].parse().map_err(|_|AgentError::Message("LCU 포트 오류".into()))?;Ok(Self{port,password:p[3].into(),http:Client::builder().danger_accept_invalid_certs(true).build()?})} fn auth(&self,b:reqwest::RequestBuilder)->reqwest::RequestBuilder{b.basic_auth("riot",Some(&self.password))} async fn request(&self,method:reqwest::Method,path:&str,body:Option<Value>)->AgentResult<Value>{let u=format!("https://127.0.0.1:{}{}",self.port,path);let b=self.http.request(method,&u);let b=self.auth(b);let b=if let Some(v)=body{b.json(&v)}else{b};let r=b.send().await?;let ok=r.status().is_success();let text=r.text().await.unwrap_or_default();if !ok{return Err(AgentError::Message(format!("LCU {}: {}",path,text.chars().take(180).collect::<String>())))}Ok(serde_json::from_str(&text).unwrap_or(Value::Null))} async fn action(&self,action:&str,p:&Value,c:&Config)->AgentResult<Value>{let (m,path,body) = match action {"ping"=>(reqwest::Method::GET,"/lol-summoner/v1/current-summoner".to_string(),None),"accept_match"=>(reqwest::Method::POST,"/lol-matchmaking/v1/ready-check/accept".to_string(),None),"decline_match"=>(reqwest::Method::POST,"/lol-matchmaking/v1/ready-check/decline".to_string(),None),"reconnect"=>(reqwest::Method::POST,"/lol-gameflow/v1/reconnect".to_string(),None),"queue_start"=>(reqwest::Method::POST,"/lol-lobby/v2/lobby/matchmaking/search".to_string(),None),"queue_cancel"=>(reqwest::Method::DELETE,"/lol-lobby/v2/lobby/matchmaking/search".to_string(),None),"leave_lobby"=>(reqwest::Method::DELETE,"/lol-lobby/v2/lobby".to_string(),None),"party_ready"=>(reqwest::Method::PUT,"/lol-lobby/v1/parties/ready".to_string(),Some(json!({"ready":true}))),"champ_reroll"=>(reqwest::Method::POST,"/lol-champ-select/v1/session/my-selection/reroll".to_string(),None),"quit_client"=>(reqwest::Method::POST,"/process-control/v1/process/quit".to_string(),None),"set_status"=>{let t=p.get("text").and_then(Value::as_str).unwrap_or("");if t.len()>128{return Err(AgentError::Message("상태 메시지가 너무 깁니다.".into()))} (reqwest::Method::PUT,"/lol-chat/v1/me".to_string(),Some(json!({"statusMessage":t})))},"reset_status"=>(reqwest::Method::PUT,"/lol-chat/v1/me".to_string(),Some(json!({"statusMessage":"𝗬𝘂𝗺𝗺𝗶 𝗖𝗹𝗶𝗲𝗻𝘁"}))),"champ_select_action"=>{let id=p.get("action_id").and_then(Value::as_i64).ok_or_else(||AgentError::Message("action_id가 필요합니다.".to_string()))?;let champ=p.get("champion_id").and_then(Value::as_i64).ok_or_else(||AgentError::Message("champion_id가 필요합니다.".to_string()))?;(reqwest::Method::PATCH,format!("/lol-champ-select/v1/session/actions/{}",id),Some(json!({"championId":champ})))},_=>return Err(AgentError::Message(format!("action '{}'은 추가 LCU 매핑이 필요합니다.",action)))};let _=c;self.request(m,&path,body).await} }

fn lockfile_path(c:&Config)->Option<PathBuf>{if let Some(raw)=&c.lockfile_path{let p=raw.var_expand();if Path::new(&p).exists(){return Some(PathBuf::from(p))}};[r"C:\Riot Games\League of Legends\lockfile",r"C:\Riot Games\League of Legends\Game\lockfile"].iter().map(PathBuf::from).find(|p|p.exists())}
trait VarExpand{fn var_expand(&self)->String;} impl VarExpand for String{fn var_expand(&self)->String{let mut s=self.clone();for (k,v) in std::env::vars(){s=s.replace(&format!("%{}%",k),&v);}s}}

#[derive(Serialize,Deserialize)] struct Session{session_id:String,ws_token:String,saved_at_utc:u64,relay_base_url:String}
fn session_path()->PathBuf{dirs::data_local_dir().unwrap_or_else(std::env::temp_dir).join("YummiAgent").join("relay-session.json")}
fn new_session(c:&Config)->Session{Session{session_id:Uuid::new_v4().to_string(),ws_token:B64.encode(uuid::Uuid::new_v4().as_bytes()),saved_at_utc:SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_secs(),relay_base_url:c.relay_public_base_url.trim_end_matches('/').to_lowercase()}}
fn open_login_url(url: &str) { #[cfg(windows)] { let _ = std::process::Command::new("cmd").args(["/C", "start", "", url]).spawn(); } }
fn load_session(c:&Config)->Option<Session>{let s=fs::read_to_string(session_path()).ok()?;let v:Value=serde_json::from_str(&s).ok()?;let p=v.get("Payload")?.as_str()?;let plain=dpapi_unprotect(p)?;let row:Session=serde_json::from_str(&plain).ok()?;let now=SystemTime::now().duration_since(UNIX_EPOCH).ok()?.as_secs();if row.relay_base_url!=c.relay_public_base_url.trim_end_matches('/').to_lowercase()||now.saturating_sub(row.saved_at_utc)>c.saved_session_max_age_days*86400{return None}Some(row)}
fn save_session(s:&Session){if let Some(p)=session_path().parent(){let _=fs::create_dir_all(p);}if let Ok(plain)=serde_json::to_string(s){if let Some(enc)=dpapi_protect(&plain){let _=fs::write(session_path(),serde_json::to_string(&json!({"V":3,"Payload":enc})).unwrap());}}}
fn dpapi_protect(s: &str) -> Option<String> {
    #[cfg(windows)]
    {
        use windows::Win32::Security::Cryptography::{CryptProtectData, CRYPT_INTEGER_BLOB};
        let mut input = CRYPT_INTEGER_BLOB { cbData: s.len() as u32, pbData: s.as_ptr() as *mut u8 };
        let mut output = CRYPT_INTEGER_BLOB::default();
        unsafe {
            CryptProtectData(&mut input, None, None, None, None, 0, &mut output).ok()?;
            let bytes = std::slice::from_raw_parts(output.pbData, output.cbData as usize);
            let encoded = B64.encode(bytes);
            return Some(encoded);
        }
    }
    #[cfg(not(windows))]
    { let _ = s; None }
}

fn dpapi_unprotect(s: &str) -> Option<String> {
    #[cfg(windows)]
    {
        use windows::Win32::Security::Cryptography::{CryptUnprotectData, CRYPT_INTEGER_BLOB};
        let bytes = B64.decode(s).ok()?;
        let mut input = CRYPT_INTEGER_BLOB { cbData: bytes.len() as u32, pbData: bytes.as_ptr() as *mut u8 };
        let mut output = CRYPT_INTEGER_BLOB::default();
        unsafe {
            CryptUnprotectData(&mut input, None, None, None, None, 0, &mut output).ok()?;
            let value = String::from_utf8_lossy(std::slice::from_raw_parts(output.pbData, output.cbData as usize)).to_string();
            return Some(value);
        }
    }
    #[cfg(not(windows))]
    { let _ = s; None }
}

#[tauri::command] async fn load_config(state:State<'_,Arc<AgentState>>)->std::result::Result<Config,String>{Ok(state.config.read().await.clone())}
#[tauri::command] async fn save_config(app:AppHandle,state:State<'_,Arc<AgentState>>,mut config:Config)->std::result::Result<(),String>{config.normalize();sync_windows_startup(config.run_at_windows_startup).map_err(|e|e.to_string())?;config.save().map_err(|e|e.to_string())?;*state.config.write().await=config.clone();state.ui.lock().await.config=config;state.emit(&app).await;Ok(())}
async fn start_agent_inner(app:AppHandle,state:Arc<AgentState>)->std::result::Result<(),String>{if state.cancel.lock().await.is_some(){return Ok(())}let c=state.config.read().await.clone();let (tx,mut rx)=tokio::sync::watch::channel(false);*state.cancel.lock().await=Some(tx);state.log(&app,"Relay 연결 시작").await;let st=state.clone();tokio::spawn(async move{let saved=load_session(&c);let needs_login=saved.is_none();let s=saved.unwrap_or_else(||new_session(&c));loop{if *rx.borrow(){break}match connect_relay(&app,&st,&c,&s,&mut rx,needs_login).await{Ok(_)=>break,Err(e)=>{st.log(&app,format!("Relay 오류: {}",e)).await;sleep(Duration::from_secs(3)).await}}}});Ok(())}
#[tauri::command] async fn start_agent(app:AppHandle,state:State<'_,Arc<AgentState>>)->std::result::Result<(),String>{start_agent_inner(app,state.inner().clone()).await}
#[tauri::command] async fn stop_agent(app:AppHandle,state:State<'_,Arc<AgentState>>)->std::result::Result<(),String>{if let Some(tx)=state.cancel.lock().await.take(){let _=tx.send(true);}let mut u=state.ui.lock().await;u.relay=false;u.lcu=false;u.status="중지됨".into();drop(u);state.emit(&app).await;Ok(())}
#[tauri::command] async fn relogin(app:AppHandle,state:State<'_,Arc<AgentState>>)->std::result::Result<(),String>{let _=fs::remove_file(session_path());stop_agent(app.clone(),state.clone()).await?;start_agent(app,state).await}
#[tauri::command] async fn submit_oauth_code(app:AppHandle,state:State<'_,Arc<AgentState>>,code:String)->std::result::Result<(),String>{let code=code.trim().to_string();if code.len()!=6||!code.chars().all(|c|c.is_ascii_digit()){return Err("6자리 숫자 코드를 입력하세요.".into())}if let Some(tx)=state.oauth_tx.lock().await.as_ref(){tx.send(code).await.map_err(|_|"Relay 연결이 없습니다.".to_string())?;state.log(&app,"Discord 연결 코드 전송됨").await;Ok(())}else{Err("먼저 연결을 시작하세요.".into())}}
#[tauri::command] async fn recent_match(state:State<'_,Arc<AgentState>>)->std::result::Result<Value,String>{let c=state.config.read().await.clone();let path=lockfile_path(&c).ok_or("League Client가 실행 중이 아닙니다.")?;let l=Lcu::from_lockfile(&path).map_err(|e|e.to_string())?;let me=l.request(reqwest::Method::GET,"/lol-summoner/v1/current-summoner",None).await.map_err(|e|e.to_string())?;let puuid=me.get("puuid").and_then(Value::as_str).ok_or("소환사 PUUID를 찾지 못했습니다.")?;let games=l.request(reqwest::Method::GET,&format!("/lol-match-history/v1/products/lol/{puuid}/matches?begIndex=0&endIndex=1"),None).await.map_err(|e|e.to_string())?;let game=games.pointer("/games/games/0").cloned().ok_or("최근 경기가 없습니다.")?;let p=game.get("participants").and_then(Value::as_array).and_then(|rows|rows.iter().find(|p|p.get("puuid").and_then(Value::as_str)==Some(puuid))).cloned().unwrap_or(Value::Null);let stats=p.get("stats").cloned().unwrap_or(Value::Null);Ok(json!({"champion":p.get("championName").or_else(||p.get("championId")).cloned().unwrap_or(Value::String("알 수 없음".into())),"win":stats.get("win").cloned().unwrap_or(Value::Null),"kills":stats.get("kills").cloned().unwrap_or(Value::Null),"deaths":stats.get("deaths").cloned().unwrap_or(Value::Null),"assists":stats.get("assists").cloned().unwrap_or(Value::Null),"duration":game.get("gameDuration").cloned().unwrap_or(Value::Null),"created_at":game.get("gameCreationDate").cloned().unwrap_or(Value::Null)}))}
async fn connect_relay(app:&AppHandle,state:&Arc<AgentState>,c:&Config,s:&Session,rx:&mut tokio::sync::watch::Receiver<bool>,needs_login:bool)->AgentResult<()> {let url=c.ws_url(&s.session_id)?;let (mut ws,_)=connect_async(url).await.map_err(|e|AgentError::Message(e.to_string()))?;ws.send(Message::Text(json!({"type":"auth","ws_token":s.ws_token}).to_string().into())).await.map_err(|e|AgentError::Message(e.to_string()))?;let (oauth_tx,mut oauth_rx)=mpsc::channel::<String>(1);*state.oauth_tx.lock().await=Some(oauth_tx);{let mut u=state.ui.lock().await;u.relay=true;u.oauth_pending=needs_login;u.status=if needs_login{"브라우저에서 Discord 로그인 중…".into()}else{"저장된 Discord 세션 복원 중…".into()};}if needs_login{open_login_url(&c.login_url(&s.session_id));}state.emit(app).await;save_session(s);while !*rx.borrow(){if let Ok(Some(code))=timeout(Duration::from_millis(250),oauth_rx.recv()).await{ws.send(Message::Text(json!({"type":"complete_oauth_link","code":code}).to_string().into())).await.map_err(|e|AgentError::Message(e.to_string()))?;}if let Ok(Some(msg))=timeout(Duration::from_millis(250),ws.next()).await{match msg.map_err(|e|AgentError::Message(e.to_string()))?{Message::Text(t)=>{handle_relay_message(app,state,c,&mut ws,&t).await?},Message::Close(_)=>break,_=>{}}}}*state.oauth_tx.lock().await=None;Ok(())}
async fn handle_relay_message<S>(app:&AppHandle,state:&Arc<AgentState>,c:&Config,ws:&mut S,text:&str)->AgentResult<()>
where S: Sink<Message> + Unpin, S::Error: std::fmt::Display
{let v:Value=serde_json::from_str(text)?;if v.get("type").and_then(Value::as_str)==Some("command"){let action=v.get("action").and_then(Value::as_str).unwrap_or("");let req=v.get("request_id").cloned().unwrap_or(Value::Null);let p=v.get("payload").cloned().unwrap_or(json!({}));let result=if !allowed(action){json!({"ok":false,"message":"unknown action"})}else if action=="launch_client"{json!({"ok":false,"message":"launch_client requires Windows launcher integration"})}else if let Some(path)=lockfile_path(c){let _guard=state.command_lock.lock().await;match Lcu::from_lockfile(&path){Ok(l)=>match l.action(action,&p,c).await{Ok(_)=>json!({"ok":true,"message":"완료"}),Err(e)=>json!({"ok":false,"message":e.to_string()})},Err(e)=>json!({"ok":false,"message":e.to_string()})}}else{json!({"ok":false,"message":"LCU 미연결"})};let ok=result.get("ok").and_then(Value::as_bool).unwrap_or(false);ws.send(Message::Text(json!({"type":"command_result","request_id":req,"result":result,"ok":ok}).to_string().into())).await.map_err(|e|AgentError::Message(e.to_string()))?;state.log(app,format!("명령 실행: {}",action)).await}else if v.get("type").and_then(Value::as_str)==Some("session_bound"){let mut u=state.ui.lock().await;u.oauth_pending=false;u.discord_id=v.get("discord_id").and_then(Value::as_u64);u.discord_name=v.get("discord_name").and_then(Value::as_str).map(str::to_string).or_else(||v.get("username").and_then(Value::as_str).map(str::to_string));u.discord_avatar=v.get("discord_avatar").and_then(Value::as_str).map(str::to_string).or_else(||v.get("avatar_url").and_then(Value::as_str).map(str::to_string));u.status="Discord 연결 완료 — LCU 확인 중…".into();drop(u);state.emit(app).await;state.log(app,"Discord 연결 완료").await}Ok(())}

#[derive(Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
struct UpdateTarget { version: String, url: Option<String>, patch_url: Option<String>, patch_from: Option<String>, sha256: Option<String>, patch_sha256: Option<String>, executable: Option<String> }
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct UpdateManifest { tauri: Option<UpdateTarget> }
impl UpdateManifest { fn select_tauri(self)->Option<UpdateTarget>{ self.tauri } }
fn version_tuple(v: &str) -> Option<(u64,u64,u64)> { let mut p=v.trim().split('.').map(|x|x.parse::<u64>().ok()); Some((p.next()??,p.next().unwrap_or(Some(0))?,p.next().unwrap_or(Some(0))?)) }
fn is_newer(remote:&str, current:&str)->bool { match (version_tuple(remote),version_tuple(current)){(Some(a),Some(b))=>a>b,_=>false} }
fn verify_hash(bytes:&[u8], expected:&str)->bool { let Some(expected)=expected.strip_prefix("0x").or(Some(expected)) else{return false}; if expected.trim().len()!=64{return false}; let mut h=Sha256::new();h.update(bytes);format!("{:x}",h.finalize()).eq_ignore_ascii_case(expected.trim()) }
fn safe_extract<R: Read + std::io::Seek>(archive:&mut zip::ZipArchive<R>, out:&Path)->AgentResult<()> { for i in 0..archive.len(){let mut f=archive.by_index(i).map_err(|e|AgentError::Message(e.to_string()))?;let Some(name)=f.enclosed_name() else{continue};let dst=out.join(name);if f.is_dir(){fs::create_dir_all(&dst)?}else{if let Some(parent)=dst.parent(){fs::create_dir_all(parent)?}let mut o=fs::File::create(dst)?;std::io::copy(&mut f,&mut o)?;}}Ok(()) }
async fn apply_update(manifest:UpdateManifest)->AgentResult<bool>{let manifest=match manifest.select_tauri(){Some(v)=>v,None=>return Ok(false)};let current=env!("CARGO_PKG_VERSION");if !is_newer(&manifest.version,current){return Ok(false)}let use_patch=manifest.patch_from.as_deref()==Some(current)&&manifest.patch_url.is_some();let url=if use_patch{manifest.patch_url}else{manifest.url};let hash=if use_patch{manifest.patch_sha256}else{manifest.sha256};let (Some(url),Some(hash))=(url,hash)else{return Ok(false)};let parsed=url::Url::parse(&url).map_err(|e|AgentError::Message(e.to_string()))?;if parsed.scheme()!="https"{return Ok(false)}let bytes=Client::new().get(parsed).send().await?.bytes().await?;if !verify_hash(&bytes,&hash){return Err(AgentError::Message("자동 업데이트 SHA-256 검증 실패".into()))}let work=std::env::temp_dir().join("yummi-lcu-update").join(&manifest.version);if work.exists(){fs::remove_dir_all(&work)?}fs::create_dir_all(&work)?;let extract=work.join("extract");fs::create_dir_all(&extract)?;let mut zip=zip::ZipArchive::new(Cursor::new(bytes)).map_err(|e|AgentError::Message(e.to_string()))?;safe_extract(&mut zip,&extract)?;let exe_name=manifest.executable.as_deref().unwrap_or("yummi-lcu-tauri.exe");if !exe_name.eq_ignore_ascii_case("yummi-lcu-tauri.exe"){return Err(AgentError::Message("Tauri 대상 실행 파일이 올바르지 않습니다.".into()))}let source=std::iter::once(extract.join(exe_name)).chain(fs::read_dir(&extract).ok().into_iter().flatten().filter_map(|x|x.ok().map(|e|e.path()).filter(|p|p.is_dir()).map(|p|p.join(exe_name)))).find(|p|p.exists()).ok_or_else(||AgentError::Message("업데이트 ZIP에 Tauri 실행 파일이 없습니다.".into()))?;let target=std::env::current_exe().map_err(|e|AgentError::Message(e.to_string()))?;if !target.file_name().is_some_and(|n|n.eq_ignore_ascii_case(exe_name)){return Err(AgentError::Message("현재 설치는 Tauri 배포물이 아닙니다.".into()))}let target_dir=target.parent().ok_or_else(||AgentError::Message("앱 폴더를 찾지 못했습니다.".into()))?;let script=work.join("apply-update.cmd");let src=source.parent().unwrap().display();let dst=target_dir.display();let exe=target.display();let text=format!("@echo off\r\ntimeout /t 2 /nobreak >nul\r\nrobocopy \"{src}\" \"{dst}\" /E /XF agent.json >nul\r\nif errorlevel 8 exit /b 1\r\nstart \"\" \"{exe}\"\r\ndel \"%~f0\"\r\n");fs::write(&script,text)?;#[cfg(windows)]{use std::os::windows::process::CommandExt;std::process::Command::new("cmd.exe").args(["/C",script.to_string_lossy().as_ref()]).creation_flags(0x08000000).spawn().map_err(|e|AgentError::Message(e.to_string()))?;}Ok(true)}
async fn auto_update_on_startup(app:AppHandle,state:Arc<AgentState>){let c=state.config.read().await.clone();if !c.check_updates_on_startup||!c.auto_update_enabled{return}let Some(url)=c.update_manifest_url else{return};sleep(Duration::from_secs(2)).await;let Ok(response)=Client::new().get(&url).send().await else{return};let Ok(manifest)=response.json::<UpdateManifest>().await else{return};match apply_update(manifest).await{Ok(true)=>{state.log(&app,"새 버전을 설치하고 재시작합니다.").await;app.exit(0)},Ok(false)=>{},Err(e)=>state.log(&app,format!("자동 업데이트 실패: {}",e)).await}}

#[cfg_attr(mobile, tauri::mobile_entry_point)] pub fn run()->std::result::Result<(),tauri::Error>{let c=Config::load();let _=sync_windows_startup(c.run_at_windows_startup);let st=Arc::new(AgentState{config:RwLock::new(c.clone()),ui:Mutex::new(UiState::new(c)),cancel:Mutex::new(None),oauth_tx:Mutex::new(None),command_lock:Mutex::new(())});let update_state=st.clone();let connect_state=st.clone();tauri::Builder::default().plugin(tauri_plugin_opener::init()).manage(st).invoke_handler(tauri::generate_handler![load_config,save_config,start_agent,stop_agent,relogin,submit_oauth_code,recent_match]).setup(move|app|{let handle=app.handle().clone();tauri::async_runtime::spawn(auto_update_on_startup(handle.clone(),update_state));tauri::async_runtime::spawn(async move{let _=start_agent_inner(handle,connect_state).await;});Ok(())}).run(tauri::generate_context!())}

#[cfg(test)] mod tests { use super::*; #[test] fn whitelist_is_compatible(){assert!(allowed("ping"));assert!(allowed("invite_party_members"));assert!(!allowed("arbitrary_http"));} #[test] fn https_upgrade_preserves_local(){assert_eq!(Config::secure_url("http://localhost:8790"),"http://localhost:8790");assert_eq!(Config::secure_url("http://example.com/a"),"https://example.com/a");} #[test] fn lockfile_rejects_bad_shape(){let p=std::env::temp_dir().join(format!("yummi-{}.lock",Uuid::new_v4()));fs::write(&p,"bad").unwrap();assert!(Lcu::from_lockfile(&p).is_err());let _=fs::remove_file(p);} #[test] fn sha256_helper_compiles(){let mut h=Sha256::new();h.update(b"yummi");assert_eq!(format!("{:x}",h.finalize()).len(),64);}}
