<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>YummiLcu.Core</RootNamespace>
    <AssemblyName>YummiLcu.Core</AssemblyName>
  </PropertyGroup>
</Project>
